---
.travis.yml:
  extras:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.6.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.7.0"
.puppet-lint.rc:
  extra_disabled_lint_checks:
  - '--no-quoted_booleans-check'
